---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

```


```{r}
data("rest_inspec")

rest_inspec <- 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  filter(
    grade %in% c("A", "B", "C"),
    boro != "Missing"
  ) %>% 
  drop_na() 


```

Column {data-width=650}
-------------------------------------------------------------------------------

### Distribution of Health Inspection Scores for Chinese Restaurants

```{r}
rest_inspec %>%
  filter(cuisine_description == "Chinese") %>% 
  group_by(boro) %>% 
  plot_ly(
    x = ~boro, y = ~score, color = ~boro,
    type = "violin", colors = "viridis"
  ) %>% 
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Health Inspection Score")
  )
  

```


Column {data-width=350}
-----------------------------------------------------------------------

### Number of Chinese Restaurants by Borough

```{r}

rest_inspec %>% 
  group_by(boro) %>%
  filter(cuisine_description == "Chinese") %>% 
  distinct(dba) %>% 
  count() %>% 
  plot_ly(
    x = ~boro, y = ~n, color = ~boro, 
    type = "bar", colors = "viridis"
  ) %>% 
  layout(
    xaxis = list(title = "Borough"),
    yaxis = list(title = "Number of Chinese Restaurants")
  )
  

```

### Health Inspection Scores for Chinese Restaurants from 2013-2018

```{r}
rest_inspec %>% 
  filter(
    boro == "MANHATTAN", 
    cuisine_description == "Chinese",
  ) %>% 
  mutate(
    data_label = str_c("Restaurant: ", dba, "Score: ", score)
  ) %>% 
  plot_ly(
    x = ~grade_date, y = ~score, color = ~grade, text = ~data_label,
    type = "scatter", mode = "markers", alpha = 0.75
  ) %>% 
  layout(
    xaxis = list(title = "Year"),
    yaxis = list(title = "Health Inspection Score"),
    legend = list(title = list(text = "Grade"))
  )



```


